In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('1.xlsx')

In [3]:
df.head(10)

,Unemployment rate (Percent),1980,1981,1982,1983,1984,1985,1986,1987,1988,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Albania,5,4.2,2.8,3.3,4.4,5.9,5.4,5.2,6,...,17.1,15.2,13.7,12.3,11.5,11.7,11.5,10.8,9.5,8.8
1,Algeria,15.8,15.4,15,14.3,16.5,16.9,18.4,20.1,21.8,...,11.2,10.5,11.7,11.7,11.4,no data,no data,no data,no data,no data
2,Andorra,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,3.9,3.3,2.4,1.8,2.1,2.9,3.3,2.1,1.6,1.4
3,Argentina,3,5,4.5,5,5,6.2,6.3,6,6.5,...,6.5,8.5,8.4,9.2,9.8,11.6,8.8,6.8,6.1,7.2
4,Armenia,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,18.5,18,17.8,19,18.3,18.2,15.5,13.5,12.6,13
5,Aruba,no data,no data,no data,no data,no data,no data,19.6,14.5,5,...,7.3,7.7,8.9,7.3,5.2,8.6,8.8,4.3,4,3.9
6,Australia,6.1,5.8,7.2,10,9,8.3,8.1,8.1,7.2,...,6.1,5.7,5.6,5.3,5.2,6.5,5.1,3.7,3.7,4
7,Austria,1.6,2.2,3.1,3.7,3.8,3.6,3.1,3.8,2.7,...,6.2,6.5,5.9,5.2,4.8,5.5,6.2,4.7,5.1,5.4
8,Azerbaijan,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,5,5,5,4.9,5,7.2,6,5.6,5.5,5.4
9,"Bahamas, The",no data,no data,no data,no data,no data,no data,12.2,11.5,11,...,13.4,12.2,10.1,10.4,10.1,25.9,17.4,10.7,10.2,9.4

In [4]:
df.replace('no data', 'Nil', inplace=True)

In [5]:
df.rename(columns={df.columns[0]: 'Country'}, inplace=True)

In [6]:
df_melted = df.melt(id_vars='Country', var_name='Year', value_name='Unemployment Rate (%)')

In [7]:
df_melted.head(15)

         Country  Year Unemployment Rate (%)
0        Albania  1980                     5
1        Algeria  1980                  15.8
2        Andorra  1980                   Nil
3      Argentina  1980                     3
4        Armenia  1980                   Nil
5          Aruba  1980                   Nil
6      Australia  1980                   6.1
7        Austria  1980                   1.6
8     Azerbaijan  1980                   Nil
9   Bahamas, The  1980                   Nil
10       Bahrain  1980                   Nil
11      Barbados  1980                   Nil
12       Belarus  1980                   Nil
13       Belgium  1980                   8.3
14        Belize  1980                   Nil

In [8]:
from google.colab import files
output_file = 'unemployment_transformed.csv'
df_melted.to_csv(output_file, index=False)

files.download(output_file)

In [11]:
df_1 = pd.read_excel('/content/IMF.xls')
df_1.head()

,"Government expenditure, percent of GDP (% of GDP)",1908,1909,1910,1911,1912,1913,1914,1915,1916,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Albania,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,31.729155,30.757805,29.139476,29.161570,29.076871,29.075409,32.552481,32.124103,30.444901,29.174094
2,Algeria,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,36.947278,40.917802,37.179327,36.248542,36.249785,37.099053,37.505600,32.540084,32.699300,38.061398
3,Angola,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,32.303123,23.873171,19.423279,21.032433,18.265487,18.214289,19.993840,17.280417,19.510293,19.242327
4,Antigua and Barbuda,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,20.855637,24.827240,23.778901,22.604659,21.538746,22.122993,25.992616,23.396898,20.692064,18.443059

In [12]:
print("Current Columns:")
for idx, col in enumerate(df_1.columns):
    print(f"{idx}: {col}")

start = int(input("Enter the start index of columns to drop: "))
end = int(input("Enter the end index of columns to drop: "))

df_1 = df_1.drop(df_1.columns[start:end+1], axis=1)

Current Columns:
0: Government expenditure, percent of GDP (% of GDP)
1: 1908
2: 1909
3: 1910
4: 1911
5: 1912
6: 1913
7: 1914
8: 1915
9: 1916
10: 1917
11: 1918
12: 1919
13: 1920
14: 1921
15: 1922
16: 1923
17: 1924
18: 1925
19: 1926
20: 1927
21: 1928
22: 1929
23: 1930
24: 1931
25: 1932
26: 1933
27: 1934
28: 1935
29: 1936
30: 1937
31: 1938
32: 1939
33: 1940
34: 1941
35: 1942
36: 1943
37: 1944
38: 1945
39: 1946
40: 1947
41: 1948
42: 1949
43: 1950
44: 1951
45: 1952
46: 1953
47: 1954
48: 1955
49: 1956
50: 1957
51: 1958
52: 1959
53: 1960
54: 1961
55: 1962
56: 1963
57: 1964
58: 1965
59: 1966
60: 1967
61: 1968
62: 1969
63: 1970
64: 1971
65: 1972
66: 1973
67: 1974
68: 1975
69: 1976
70: 1977
71: 1978
72: 1979
73: 1980
74: 1981
75: 1982
76: 1983
77: 1984
78: 1985
79: 1986
80: 1987
81: 1988
82: 1989
83: 1990
84: 1991
85: 1992
86: 1993
87: 1994
88: 1995
89: 1996
90: 1997
91: 1998
92: 1999
93: 2000
94: 2001
95: 2002
96: 2003
97: 2004
98: 2005
99: 2006
100: 2007
101: 2008
102: 2009
103: 2010
104: 2011
105: 2012
106: 2013
107: 2014
108: 2015
109: 2016
110: 2017
111: 2018
112: 2019
113: 2020
114: 2021
115: 2022
116: 2023
Enter the start index of columns to drop: 1
Enter the end index of columns to drop: 13

In [14]:
id_vars = ['Government expenditure, percent of GDP (% of GDP)']

df_1_melted = df_1.melt(id_vars=id_vars, var_name='Year', value_name='GDP Growth')


df_1_melted = df_1_melted[df_1_melted['GDP Growth'] != 'no data']

In [15]:
df_1_melted.to_csv('gdp_1921-2023.csv', index=False)